version: 2.1
jobs:
  build-and-scrape:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: py-deps-{{ checksum "requirements.txt" }}
      - run:
          command: |
            # Run scraper
            pip install --upgrade pip
            pip install -r requirements.txt 
            chmod u+x RPScraper/scripts/run_daily_updates.sh 
            ./RPScraper/scripts/run_daily_updates.sh
      - save_cache:
          key: py-deps-{{ checksum "requirements.txt" }}
          paths:
            - "/venv"

orbs:
  aws-cli: circleci/aws-cli@1.0.0
workflows:
  version: 2.1
  daily-update:
    jobs:
      - build-and-scrape:
          context: aws

